=== doubleduck98/uni/dotnet/lista9/zadanie2.4.7/ListaStudentow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="MojaLista" targetNamespace="MojaLista" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ListaStudentow" type="ListaStudentowType"/>
  <xs:complexType name="AdresType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Ulica" use="required"/>
        <xs:attribute type="xs:int" name="NrDomu" use="required"/>
        <xs:attribute type="xs:int" name="Mieszkanie" use="optional"/>
        <xs:attribute type="xs:string" name="Miasto" use="required"/>
        <xs:attribute type="xs:string" name="KodPocztowy" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AdresTymczasowyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Ulica" use="required"/>
        <xs:attribute type="xs:int" name="NrDomu" use="required"/>
        <xs:attribute type="xs:int" name="Mieszkanie" use="optional"/>
        <xs:attribute type="xs:string" name="Miasto" use="required"/>
        <xs:attribute type="xs:string" name="KodPocztowy" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ZajeciaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="Nazwa" use="required"/>
        <xs:attribute type="xs:int" name="OcenaZCwiczen" use="optional"/>
        <xs:attribute type="xs:int" name="OcenaZWykladu" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ListaZajecType">
    <xs:sequence>
      <xs:element type="ZajeciaType" name="Zajecia" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StudentType">
    <xs:sequence>
      <xs:element type="AdresType" name="Adres"/>
      <xs:element type="AdresTymczasowyType" name="AdresTymczasowy"/>
      <xs:element type="ListaZajecType" name="ListaZajec"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Imie" use="required"/>
    <xs:attribute type="xs:string" name="Nazwisko" use="required"/>
    <xs:attribute type="xs:date" name="DataUrodzenia" use="required"/>
    <xs:attribute type="xs:string" name="AdresEmail" use="required"/>
  </xs:complexType>
  <xs:complexType name="ListaStudentowType">
    <xs:sequence>
      <xs:element type="StudentType" name="Student" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== doubleduck98/uni/dotnet/lista9/zadanie2.4.2-3/ZlaListaStudentow.xml
<?xml version="1.0" encoding="utf-8"?>
<ListaStudentow xmlns="MojaLista" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="MojaLista ListaStudentow.xsd">
    <Student Imie="Szymon" Nazwisko="1998-11-16" DataUrodzenia="Zienkiewicz" AdresEmail="szipi@gmail.com">
        <Adres Ulica="Długa" NrDomu="21" Mieszkanie="2" Miasto="Wrocław" KodPocztowy="53-657"/>
        <AdresTymczasowy Ulica="J.Matejki" NrDomu="2" Mieszkanie="5" Miasto="Tarnobrzeg" KodPocztowy="39-400"/>
        <ListaZajec>
            <Zajecia Nazwa="Algorytmy i struktury danych" OcenaZCwiczen="4" OcenaZWykladu="3"/>
            <Zajecia Nazwa="Programowanie pod Windows" OcenaZCwiczen="5"/>
        </ListaZajec>
    </Student>
    <Student Imie="Adam" Nazwisko="Abacki" DataUrodzenia="1996-05-21" AdresEmail="aaxd@googlemail.com">
        <Adres Ulica="Krótka" NrDomu="2" Miasto="Wrocław" KodPocztowy="55-010"/>
        <AdresTymczasowy Ulica="Prądnicka" NrDomu="75" Mieszkanie="Piąte" Miasto="Kraków" KodPocztowy="31-215"/>
        <ListaZajec>
            <Zajecia Nazwa="Algorytmy i struktury danych" OcenaZCwiczen="5" OcenaZWykladu="5"/>
            <Zajecia Nazwa="Programowanie pod Windows" OcenaZCwiczen="3" OcenaZWykladu="4"/>
        </ListaZajec>
    </Student>
</ListaStudentow>
